[versions]
# https://developer.android.com/studio/releases/build-tools.html#notes
buildTools = "35.0.0"

minSdk = "21"

compileSdk = "35"
compileSdkPreview = "VanillaIceCream"

compileSdkExtension = "13"

targetSdk = "35"
targetSdkPreview = "VanillaIceCream"

ndk = "27.1.12297006"
cmake = "3.22.1"

versionCode = "63"
versionName = "1.17.1_unpublished"

[libraries]

[bundles]

[plugins]